# Generated by Django 4.2 on 2023-04-09 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_alter_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
    ]
