# Generated by Django 4.2 on 2023-04-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_alter_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='./assets/1169.jpg', upload_to='./assets'),
        ),
    ]
