# Generated by Django 4.2 on 2023-04-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0009_remove_order_amount_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_email',
            field=models.CharField(max_length=100),
        ),
    ]
