# Generated by Django 4.2 on 2023-06-04 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0010_alter_order_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
