# Generated by Django 4.2 on 2023-07-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0014_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('red', 'Красный'), ('yellow', 'Желтый'), ('blue', 'Синий'), ('black', 'черный'), ('white', 'белый'), ('green', 'зелёный'), ('default', 'другое')], default='default', max_length=100),
        ),
    ]
