# Generated by Django 4.2 on 2023-07-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0015_alter_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tupe',
            field=models.CharField(choices=[('cap', 'кепка'), ('jamper', 'свитер'), ('T-shirt', 'футболка'), ('glass', 'очки'), ('skirt', 'юбка'), ('pants', 'штаны')], default='default', max_length=100),
        ),
    ]
