# Generated by Django 4.2 on 2023-07-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0017_alter_product_tupe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tupe',
            new_name='type',
        ),
    ]
